<div class="row" style="padding-top:40px;">
	<h3 class="text-center" >READY TO CHAT CHAT CHAT? </h3>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="panel panel-info">
			<div class="panel-heading">
				RECENT CHAT HISTORY
			</div>
			<div class="js_msglist">
				<?php require('apps/message_list.php'); ?>
			</div>
			<?php require('apps/input.php'); ?>
		</div>
	</div>	
	<div class="col-md-4">
		<?php require('apps/online.php'); ?>
	</div>	
</div>
