
<div class="row">
	<div class="col-md-9">
		<div class="chat-box">
				<div class="panel-heading">
					<!-- <h3>Recent chat history</h3> -->
				</div>
			<div id="scrollbox">
				<div class="js_msglist">
					<?php require('apps/message_list.php'); ?>
				</div>
			</div>
		</div>
		<?php require('apps/input.php'); ?>
	</div>	
	<div class="col-md-3">
		<?php require('apps/online.php'); ?>
	</div>	
</div>


